[package]
name = "poe-api"
version = "0.0.1"
authors = ["Tanner Donovan <ttdonovan@gmail.com>"]
description = "Client for Path of Exile API and WWW"

[dependencies]
reqwest = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
clap = "2.29.0"
